version: 2.1

jobs:
  test:
    working_directory: ~/ethlance
    docker:
      # Primary container image where all steps run.
      - image: 487920318758.dkr.ecr.us-west-2.amazonaws.com/cljs-web3-ci:node-16.15.1
      # Secondary container images on common network.
      - image: trufflesuite/ganache:v7.6.0
        command: [-v -m "easy leave proof verb wait patient fringe laptop intact opera slab shine", -p 8549, -l 8000000, -b 1, --chain.allowUnlimitedContractSize=true]
      - image: district0x/ipfs-daemon:latest
      - image: postgres:latest
        environment:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: ethlanceuser
          POSTGRES_DB: ethlance
    steps:
      - checkout
      - restore_cache:
          name: Restore ethlance npm package cache
          keys:
            - npm-dependencies-ethlance-{{ checksum "yarn.lock" }}
      - run:
          name: Install ethlance node modules
          command: yarn deps
      - save_cache:
          name: Save ethlance npm package cache
          key: npm-dependencies-ethlance-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Deploy contracts
          command: npx truffle migrate --network ganache --reset
      - run:
          name: Run test suite
          command: bb run-server-tests

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          context: district0x
